const Data = [
  {
    id: 1,
    image: "/image.png",
    name: "Brushed Raglan Sweatshirt",
    type: "Sweater",
    category: "Female",
    price: "$121",
    description: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: 2,
    image: "/image0.png",
    name: "Flex Sweatpants",
    type: "Sweater",
    category: "Female",
    price: "$313",
    description: "Lorem ipsum dolor sit fdex consectetur",
  },
  {
    id: 3,
    image: "/image1.png",
    name: "Flex Sweatshirt",
    type: "Pants",
    category: "Female",
    price: "$123",
    description: "Lorem ipsum dolor sit fdex consectetur",
  },
  {
    id: 4,
    image: "/image2.png",
    name: "Raglan Sweatshirt",
    type: "Sweater",
    category: "Female",
    price: "$113",
    description: "Lorem ipsum dolor sit fdex consectetur",
  },
  {
    id: 5,
    image: "/image3.png",
    name: "Imperial Alpaca Hoodie",
    type: "Jackets",
    category: "Female",
    price: "$555",
    description: "Lorem ipsum dolor sit fdex consectetur",
  },
  {
    id: 6,
    image: "/image4.png",
    name: "Flex Push Button Bomber",
    type: "Jackets",
    category: "male",
    price: "$255",
    description: "Lorem ipsum dolor sit fdex consectetur",
  },
  {
    id: 7,
    image: "/image5.png",
    name: "Brushed Bomber",
    type: "Jackets",
    category: "Female",
    price: "$255",
    description: "Lorem ipsum dolor sit fdex consectetur",
  },
  {
    id: 8,
    image: "/image6.png",
    name: "Lite Sweatpants",
    type: "Pants",
    category: "Female",
    price: "$205",
    description: "Lorem ipsum dolor sit fdex consectetur",
  },
  {
    id: 9,
    image: "/image7.png",
    name: "Brushed Raglan Sweatshirt",
    type: "Sweater",
    category: "Female",
    price: "$239",
    description: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: 10,
    image: "/image8.png",
    name: "Pink Fleece Sweatpants",
    type: "Pants",
    category: "Female",
    price: "$139",
    description: "Lorem ipsum dolor sit amet consectetur",
  },
  {
    id: 11,
    image: "/image9.png",
    name: "Muscle Tank",
    type: "T Shirts",
    category: "Female",
    price: "$90                                       ",
    description: "Lorem ipsum dolor sit amet consectetur",
  },
];

export default Data;